name: build-and-push-image

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  build-and-push:
    name: Build Docker image and push to Docker Hub

    runs-on: ubuntu-latest

    steps:

